export const nodes = [
    {
        id: 1,
        name: "Build wireframes",
        deadline: new Date(2025, 6, 31),
        type: "Design",
        isComplete: false,
        clientNumber: "C-001",
        nodes: [],
    },
    {
        id: 2,
        name: "Develop homepage",
        deadline: new Date(2025, 7, 5),
        type: "Development",
        isComplete: true,
        clientNumber: "C-002",
        nodes: [],
    },
    {
        id: 3,
        name: "Setup backend API",
        deadline: new Date(2025, 7, 10),
        type: "Backend",
        isComplete: false,
        clientNumber: "C-003",
        nodes: [],
    },
    {
        id: 4,
        name: "UI Testing",
        deadline: new Date(2025, 7, 15),
        type: "QA",
        isComplete: true,
        clientNumber: "C-004",
        nodes: [],
    },
    {
        id: 5,
        name: "Client Review",
        deadline: new Date(2025, 7, 20),
        type: "Meeting",
        isComplete: false,
        clientNumber: "C-005",
        nodes: [],
        reportType: "Fill Report",
    },
    {
        id: 6,
        name: "Launch Website",
        deadline: new Date(2025, 7, 25),
        type: "Deployment",
        isComplete: false,
        clientNumber: "C-006",
        nodes: [],
    },
    {
        id: 7,
        name: "Code Optimization",
        deadline: new Date(2025, 7, 28),
        type: "Development",
        isComplete: true,
        clientNumber: "C-007",
        nodes: [],
    },
    {
        id: 8,
        name: "Security Audit",
        deadline: new Date(2025, 8, 2),
        type: "Security",
        isComplete: false,
        clientNumber: "C-008",
        nodes: [],
    },
    {
        id: 9,
        name: "SEO Integration",
        deadline: new Date(2025, 8, 6),
        type: "Marketing",
        isComplete: true,
        clientNumber: "C-009",
        nodes: [],
    },
    {
        id: 10,
        name: "Create User Guide",
        deadline: new Date(2025, 8, 10),
        type: "Documentation",
        isComplete: false,
        clientNumber: "C-010",
        nodes: [],
    },
    {
        id: 11,
        name: "Performance Testing",
        deadline: new Date(2025, 8, 12),
        type: "QA",
        isComplete: true,
        clientNumber: "C-011",
        nodes: [],
    },
    {
        id: 12,
        name: "Mobile Optimization",
        deadline: new Date(2025, 8, 15),
        type: "Development",
        isComplete: false,
        clientNumber: "C-012",
        nodes: [],
    },
    {
        id: 13,
        name: "Client Feedback Meeting",
        deadline: new Date(2025, 8, 18),
        type: "Meeting",
        isComplete: true,
        clientNumber: "C-013",
        nodes: [],
        reportType: "Meeting Notes",
    },
    {
        id: 14,
        name: "Bug Fixing Sprint",
        deadline: new Date(2025, 8, 20),
        type: "Development",
        isComplete: false,
        clientNumber: "C-014",
        nodes: [],
    },
    {
        id: 15,
        name: "Database Migration",
        deadline: new Date(2025, 8, 22),
        type: "Backend",
        isComplete: true,
        clientNumber: "C-015",
        nodes: [],
    },
    {
        id: 16,
        name: "Third-party Integration",
        deadline: new Date(2025, 8, 24),
        type: "API",
        isComplete: false,
        clientNumber: "C-016",
        nodes: [],
    },
    {
        id: 17,
        name: "Cross-Browser Testing",
        deadline: new Date(2025, 8, 27),
        type: "QA",
        isComplete: true,
        clientNumber: "C-017",
        nodes: [],
    },
    {
        id: 18,
        name: "Final QA Approval",
        deadline: new Date(2025, 8, 30),
        type: "QA",
        isComplete: false,
        clientNumber: "C-018",
        nodes: [],
    },
    {
        id: 19,
        name: "Marketing Strategy Planning",
        deadline: new Date(2025, 9, 2),
        type: "Marketing",
        isComplete: true,
        clientNumber: "C-019",
        nodes: [],
    },
    {
        id: 20,
        name: "Internal Team Review",
        deadline: new Date(2025, 9, 5),
        type: "Meeting",
        isComplete: false,
        clientNumber: "C-020",
        nodes: [],
        reportType: "IS Report",
    },
    {
        id: 21,
        name: "Prepare Launch Checklist",
        deadline: new Date(2025, 9, 8),
        type: "Deployment",
        isComplete: true,
        clientNumber: "C-021",
        nodes: [],
    },
    {
        id: 22,
        name: "Live Demo to Client",
        deadline: new Date(2025, 9, 12),
        type: "Presentation",
        isComplete: false,
        clientNumber: "C-022",
        nodes: [],
    },
    {
        id: 23,
        name: "Prepare Invoices",
        deadline: new Date(2025, 9, 15),
        type: "Finance",
        isComplete: true,
        clientNumber: "C-023",
        nodes: [],
    },
    {
        id: 24,
        name: "Client Onboarding Docs",
        deadline: new Date(2025, 9, 18),
        type: "Documentation",
        isComplete: false,
        clientNumber: "C-024",
        nodes: [],
    },
    {
        id: 25,
        name: "Post-launch Support",
        deadline: new Date(2025, 9, 25),
        type: "Support",
        isComplete: true,
        clientNumber: "C-025",
        nodes: [],
    },
];
